apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadupyd6355-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadupyd6355-tenant-component
    app.kubernetes.io/part-of: loadupyd6355-tenant-app
  name: loadupyd6355-tenant-component
  namespace: loadupyd6355-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadupyd6355-tenant-component
    weight: null
status: {}
